### PR TITLE
Fix event hook arguments

### LINKED ISSUE #63: Misleading documentation for event arguments
The documentation (and the functional tests) for adding a cron event with arguments uses associative array syntax:

```
*     # Schedule new cron event and pass associative arguments
*     $ wp cron event schedule cron_test '+1 hour' --foo=1 --bar=2
```

This makes no sense, because the arguments for a cron event should be a numerically indexed array of arguments that get passed as individual parameters to the event's hook when the scheduled event is triggered.

The documentation in WordPress core was updated a couple of years ago to clarify this: https://core.trac.wordpress.org/changeset/42216

If you schedule an event using the example in the documentation you end up with an event that has an associative array as its arguments and a developer who was most likely expecting the first parameter to their event's callback function to be an associative array when in fact each element of that array gets passed as separate parameters. The array keys are irrelevant but their order is not: `--foo=1 --bar=2` does not result in the same parameters being passed to the hook as `--bar=2 --foo=1`.

Luckily it's possible to use the correct numerically indexed array syntax with WP-CLI:

```
wp cron event schedule cron_test '+1 hour' --0=first --1=second
```

While this is not technically a bug in WP-CLi, the documentation and the tests make it look like one. Therefore the fix is to correct the documentation, add a warning for incorrect usage, and improve the tests.

Aside: I don't believe it's possible to pass anything other than a string to an argument. This is a separate issue beyond the scope of this ticket.

### PR DESCRIPTION
**Pull request by johnbillion**
Fixes #63

### CODE REVIEW

File: src/Cron_Event_Command.php [hunk 1]
```diff
@@ -150,11 +150,14 @@ public function list_( $args, $assoc_args ) {
...
 	 *
-	 *     # Schedule new cron event and pass associative arguments
-	 *     $ wp cron event schedule cron_test '+1 hour' --foo=1 --bar=2
+	 *     # Schedule new cron event and pass arguments
+	 *     $ wp cron event schedule cron_test '+1 hour' --0=first-parameter --1=second-parameter
 	 *     Success: Scheduled event with hook 'cron_test' for 2016-05-31 11:21:35 GMT.
 	 */
 	public function schedule( $args, $assoc_args ) {
+		if ( count( $assoc_args ) && count( array_filter( array_keys( $assoc_args ), 'is_string' ) ) ) {
+			WP_CLI::warning( 'Numeric keys should be used for the hook arguments' );
```
Comment (schlessera) [inline src/Cron_Event_Command.php:159]:
```suggestion
			WP_CLI::warning( 'Numeric keys should be used for the hook arguments.' );
```

File: features/cron.feature [hunk 2]
```diff
@@ -318,3 +318,16 @@ Feature: Manage WP-Cron events and schedules
       """
       wp_cli_test_event_1 wp_cli_test_event_1
       """
+
+  Scenario: Scheduling an event with non-numerically indexed arguments
+    When I try `wp cron event schedule wp_cli_test_args_event '+10 minutes' --foo=banana --bar=apple`
+    Then STDOUT should not be empty
+    And STDERR should be:
+      """
+      Warning: Numeric keys should be used for the hook arguments
```
Comment (schlessera) [inline features/cron.feature:327]:
```suggestion
      Warning: Numeric keys should be used for the hook arguments.
```

File: src/Cron_Event_Command.php [hunk 3]
```diff
@@ -138,7 +138,7 @@ public function list_( $args, $assoc_args ) {
 	 * : How often the event should recur. See `wp cron schedule list` for available schedule names. Defaults to no recurrence.
 	 *
 	 * [--<field>=<value>]
-	 * : Associative args for the event.
+	 * : Arguments to pass to the hook for the event.
```
Comment (schlessera) [inline src/Cron_Event_Command.php:141]:
```suggestion
	 * : Arguments to pass to the hook for the event. <field> should be a numeric key, not a string.
```

File: src/Cron_Event_Command.php [hunk 4]
```diff
@@ -150,11 +150,14 @@ public function list_( $args, $assoc_args ) {
 	 *     $ wp cron event schedule cron_test now hourly
 	 *     Success: Scheduled event with hook 'cron_test' for 2016-05-31 10:20:32 GMT.
 	 *
-	 *     # Schedule new cron event and pass associative arguments
-	 *     $ wp cron event schedule cron_test '+1 hour' --foo=1 --bar=2
+	 *     # Schedule new cron event and pass arguments
+	 *     $ wp cron event schedule cron_test '+1 hour' --0=first-parameter --1=second-parameter
```
Comment (schlessera) [inline src/Cron_Event_Command.php:154]: Using the same terminology everywhere makes it easier to understand.
```suggestion
	 *     $ wp cron event schedule cron_test '+1 hour' --0=first-argument --1=second-argument
```
