### PR TITLE
Fix documentation for the delete command.

### LINKED ISSUE #54: Description for `wp cron event delete` is incorrect
The description for `wp cron event delete` states:

> Deletes the next scheduled cron event for the given hook.

This is incorrect. This command deletes _all_ scheduled events for the given hook, not just the next one. Ref: https://github.com/wp-cli/cron-command/blob/184ce82dfd6e7284a73f039ae39cf51a5f73174e/src/Cron_Event_Command.php#L370-L379

### PR DESCRIPTION
**Pull request by johnbillion**
Fixes #54 

The assertions in the `Scheduling, running, and deleting duplicate events` scenario cover deleting a hook that has multiple events scheduled, so this is just a documentation change.

### CODE REVIEW

File: src/Cron_Event_Command.php [hunk 1]
```diff
@@ -15,7 +15,7 @@
  *     $ wp cron event run --due-now
  *     Success: Executed a total of 2 cron events.
  *
- *     # Delete the next scheduled cron event
+ *     # Delete all scheduled cron events for the given hook
```
Comment (thrijith) [inline src/Cron_Event_Command.php:18]:
```suggestion
 *     # Deletes all scheduled cron events for the given hook
```
Should it be `Deletes` based on https://github.com/wp-cli/wp-cli/issues/4542?

File: src/Cron_Event_Command.php [hunk 2]
```diff
@@ -353,7 +353,7 @@ protected static function run_event( stdClass $event ) {
 	 *
 	 * ## EXAMPLES
 	 *
-	 *     # Delete the next scheduled cron event
+	 *     # Delete all scheduled cron events for the given hook
```
Comment (thrijith) [inline src/Cron_Event_Command.php:356]:
```suggestion
	 *     # Deletes all scheduled cron events for the given hook
```

File: src/Cron_Event_Command.php (hunk 1 above)
Comment (szepeviktor) [reply src/Cron_Event_Command.php:18]: Don't you like the standard imperative??

Comment (thrijith) [reply src/Cron_Event_Command.php:18]: Just a suggestion based on [existing documentation ](https://github.com/wp-cli/cron-command/pull/62/files#diff-6c350b5369d7bf7329ce3502ab730900R347)🙂 sorry if incorrect. I'll wait for @johnbillion and @schlessera to take a final decision.

Comment (schlessera) [reply src/Cron_Event_Command.php:18]: This form would be required by WPCS for the docblocks. But here, we describe what the example does, and we've been using the standard imperative for that.
